apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    run: db
spec:
  type: ClusterIP
  ports:
  - port: 9042
    targetPort: 9042
    protocol: TCP
    name: http
  selector:
    run: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      run: db
  replicas: 1
  template:
    metadata:
      labels:
        run: db
    spec:
      containers:
      - name: db
        image: mip/db:1.0
        env:
        - name: DS_LICENSE
          value: "accept"
        ports:
        - containerPort: 9042